vich_uploader:
    db_driver: orm

    mappings:
            posts:
                uri_prefix: /uploads/posts
                upload_destination: '%kernel.project_dir%/public/uploads/posts'
                namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
